[phases.setup]
nixPkgs = [
  "python310",
  "unixODBC",  # for pyodbc
  "pkg-config", 
  "gcc",        # needed for wheel builds
  "gfortran",   # For scipy compilation
  "meson"       # For building scipy
]

[phases.install]
cmds = [
  "python3.10 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "meson --version",  # Check if meson is installed correctly
  "pkg-config --version",  # Check if pkg-config is available
  "gfortran --version",  # Check if gfortran is installed correctly
  "ls -al",  # List the files in the current directory
  "pip install --no-cache-dir -r requirements.txt"  # Disable cache
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn disaster_management.wsgi:application"
