[phases.setup]
nixPkgs = [
  "python310",
  "unixODBC",  # for pyodbc
  "pkg-config",
  "gcc"        # needed for wheel builds
]

[phases.install]
cmds = [
  "python3.10 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "ls -al",  # List the files in the current directory
  "pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn disaster_management.wsgi:application"


