# Generated by Django 4.2.21 on 2025-06-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_userlocationdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocationdetail',
            name='isTracked',
            field=models.BooleanField(default=False),
        ),
    ]
